### ISSUE TITLE
solution in javascript

### ISSUE THREAD

**Issue by rares-lupascu** [ArseniKavalchuk/multipart-x-mixed-replace-java-player#1]
hey

any idea if this is possible in plain javascript? :)

thanks

**Comment by arskov** [comment]
Hi. In my POV it depends. 
1. If you want to do it in plain javascript, I suspect you want to consume multipart/x-mixed-replace stream directly in a browser. So, the main obstacle is CORS, if you open the page with the code from one domain, and in turn the JavaScript code opens the stream from an other domain, then the multipart/x-mixed-replace stream source must reply with correct CORS. So, it looks like you cannot open arbitrary third-party webcam without appropriate CORS headers in your player which is on the page from another domain. But if you can get correct CORS headers, I'd implement the open/parse/close functionality as a Web Worker, and send messages (aka jpeg images) to the Player, the Player renders them to a Canvas
2. Another option to do it in JavaScript is to implement that like a two step process. Say you have a web page with your player. The player is the JavaScript code which gets frames via WebSocket from your backend (say it's implemented in Node.js) and renders them on Canvas via ctx2d.drawImage or whatever. When you want to open some multipart/x-mixed-replace stream, you send the URL to your backend, the backend opens the connection and consumes the stream, it parses multipart parts (aka jpeg images) and send them via WebSocket to the player, which renders them in turn.
